title: Riding Rails
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
permalink: "/:year/:i_month/:i_day/:title/"
markdown: kramdown
category_dir: ""
category_title_prefix: ""
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-seo-tag
